Allow filtering on resource request listing
PilotDataPlatform/project pull request #11
Opened 2022-08-03 13:41 UTC by gregmccoy

## Summary

Allow filtering by username or email on resource request listing API

## JIRA Issues

PILOT-1414

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [x] Yes
- [ ] No

## Test Directions

Call the listing API with filter parameters

2022-08-03 19:10 UTC, vmoshynskyi requested changes
Please check my comments.

2022-08-03 19:10 UTC, vmoshynskyi commented on project/components/resource_request/parameters.py
Please define here a separate class `ResourceRequestFilterParameters(FilterParameters)` with `Query` annotations to have query parameters isolated from internal `Filtering` classes that are used in `CRUD`s. Check how it's implemented in `ProjectFilterParameters` class.

2022-08-03 19:10 UTC, vmoshynskyi commented on tests/components/resource_request/test_views.py
> +    async def test_list_resource_requests_filter_200(
- Please rewrite this with `@pytest.mark.parametrize('parameter', ['username', 'email'])` to have isolated testing of each parameter. Check `test_list_projects_returns_project_filtered_by_parameter_full_match` test case as an example.
```suggestion
    async def test_list_resource_requests_returns_resource_request_filtered_by_parameter_full_match(
```
- Please also move this test case to the very bottom.

2022-08-03 20:08 UTC, gregmccoy commented on project/components/resource_request/parameters.py
> +    email: str = ""
I'm not understanding the point of this, I've tried testing and I don't when this would make a difference

2022-08-04 15:08 UTC, gregmccoy commented on project/components/resource_request/parameters.py
Most of this is done, same as above I think the `username: str = ''` syntax is sufficient not sure why the Query is needed

2022-08-04 15:11 UTC, gregmccoy commented on project/components/resource_request/parameters.py
> +class ResourceRequestListFilter(Filtering):
Done, IMO the doc strings are unnecessary as they don't much that you can't see from the name

2022-08-04 15:11 UTC, gregmccoy commented on tests/components/resource_request/test_views.py
> +    async def test_list_resource_requests_filter_200(
Done

2022-08-04 16:08 UTC, hugoantunes commented on project/components/resource_request/parameters.py
> +    email: str = ""
basically, empty strings are still considered valid values when None means that this field was not set.

2022-08-04 16:28 UTC, hugoantunes requested changes

2022-08-04 16:28 UTC, hugoantunes commented on project/components/resource_request/parameters.py
use Query parameters is important because allow you to get the fields from the query string without having to define them in the endpoint. 

And the same about the `Optional[str] = None` here, when you set default `''`, it will query by `username == ''`.

2022-08-04 16:41 UTC, gregmccoy commented on project/components/resource_request/parameters.py
> +    email: str = ""
@vmoshynskyi discussed on slack with Hugo a bit but wanted to know your take. Is there any scenario where what I put wouldn't work? I can still call the API without those parameters and it works as expected. Or is this just a style preference?

2022-08-05 16:18 UTC, vmoshynskyi commented on project/components/resource_request/parameters.py
> +class ResourceRequestListFilter(Filtering):
I would say that it's subjective and essentially depends on how you perceive it.
In my opinion all functions and classes that you use outside of module where it's written should normally have docstrings.
Even if it is just a line. Docstrings can always be taken from the parent class/method and expanded if necessary.
Also this text can be expanded later if some other developer will consider it insufficient.

2022-08-05 16:24 UTC, vmoshynskyi commented on project/components/resource_request/parameters.py
> +    email: str = ""
If we judge only by the principle works or doesn't work. Then yes in the current situation it will work.
But the point is about attitude to data. An empty string is not the same as `None`.
Empty string is a `str` instance with `0` length. While `None` means that there's no value at all or/and it has not been set.

If you translate it to a query params, then agree that this
```
GET /resource/?username=&email=
```
is not the same as this
```
GET /resource/
```
The first query means filter out the documents with empty username and email fields. While second means return all without filtering.

Also, with an empty string, the generated openapi creates a not logical description.
<img width="528" alt="Screenshot" src="https://user-images.githubusercontent.com/454686/183119925-540e8b02-fa7a-46f7-ab7b-ec218d22cf4e.png">
It looks like something is not written there.

2022-08-05 16:26 UTC, vmoshynskyi commented on project/components/resource_request/parameters.py
In addition to what Hugo wrote, `Query` allows to define additional validation for each parameter. You can check more details [here](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/).

2022-08-05 16:33 UTC, vmoshynskyi commented on tests/components/resource_request/test_views.py
> +    async def test_list_resource_requests_filter_200(
Could you please consider the test case name I've suggested? You can update it in a way you want.
The point is to have better understanding on what is directly tested in the test. Check that `resource_requests_filter_200` is a small part of what the test actually tests.

2022-08-05 16:53 UTC, gregmccoy commented on project/components/resource_request/parameters.py
> +    email: str = ""
I've made the change

2022-08-05 16:54 UTC, gregmccoy commented on project/components/resource_request/parameters.py
I've made this change. Aren't `Optional[str] = None` and `Optional[str] = Query(default=None)` equivalent though? That's the impression I got from the docs.

2022-08-05 16:56 UTC, gregmccoy commented on tests/components/resource_request/test_views.py
> +    async def test_list_resource_requests_filter_200(
I've made this change. I'm not a fan of the super long names, I thought mine gave sufficient info

2022-08-05 17:24 UTC, vmoshynskyi approved these changes
Thank you!

2022-08-05 17:25 UTC, merged