Adding new fields to resource request
PilotDataPlatform/project pull request #45
Opened 2022-10-27 16:59 UTC by gregmccoy

## Summary

Adding vm_connections and message fields to the resource request table

## JIRA Issues

PILOT-1836

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [x] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2022-10-28 16:38 UTC, vmoshynskyi requested changes
Please check my comments.
Also please remove `tests/pytest.ini` file. `[tool.pytest.ini_options]` section in `pyproject.toml` file should be used for that.

2022-10-28 16:38 UTC, vmoshynskyi commented on project/components/resource_request/models.py
> +    message = Column(String(length=100), nullable=True)
- Please use `VARCHAR` here for a better understanding that `varchar` data type will be used in db.
- I would suggest to increase length at least to 256 since 100 it might be not enough for a message.
```suggestion
    message = Column(VARCHAR(length=256), nullable=True)
```

2022-10-28 16:38 UTC, vmoshynskyi commented on project/components/resource_request/models.py
> +    vm_connections = Column(JSON(), nullable=True)
I would suggest to use `JSONB` just in case we will need to index/query this data later.
```suggestion
    vm_connections = Column(JSONB(), nullable=True)
```

2022-10-28 16:38 UTC, vmoshynskyi commented on project/components/resource_request/schemas.py
> +    message: str = None
Use optional str typing for nullable values:
```suggestion
    message: str | None = None
```

2022-10-28 16:38 UTC, vmoshynskyi commented on project/components/resource_request/schemas.py
>      completed_at: datetime = None
Please also fix here:
```suggestion
    completed_at: datetime | None = None
```

2022-10-28 16:38 UTC, vmoshynskyi commented on project/components/resource_request/schemas.py
> +    vm_connections: dict = None
`dict` is a parametric type and should not be used without params:
```suggestion
    vm_connections: dict[str, Any] | None = None
```

2022-10-28 16:38 UTC, vmoshynskyi commented on tests/components/resource_request/test_views.py
> +        }
Please add these additional `vm_connections` and `message` fields into `fixtures.components.resource_request.ResourceRequestFactory` factory (check `generate`, `create`, `bulk_create` methods).
And use that methods to generate resource request objects.

2022-10-28 16:38 UTC, vmoshynskyi commented on tests/components/resource_request/test_views.py
> +    async def test_create_resource_request_connections_200(
There's already test `test_create_resource_request_creates_new_resource_request` that validates creation.
If there is a need to check the availability of `vm_connections` field then please name tests according to the actions performed in assert.
Something like `test_create_resource_request_returns_object_with_vm_connections_field_in_response`.
Treat test function name as an explanation and it's okay if it's long.

2022-10-28 17:45 UTC, gregmccoy commented on migrations/versions/0008_adding_vm_connectons_and_message_fields_.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Done

2022-10-28 17:45 UTC, gregmccoy commented on project/components/resource_request/models.py
> +    message = Column(String(length=100), nullable=True)
I've updated it, though from what I see it really makes no difference. I'm leaving the length as is as that comes from the requirements.

2022-10-28 17:46 UTC, gregmccoy commented on project/components/resource_request/models.py
> +    vm_connections = Column(JSON(), nullable=True)
Done

2022-10-28 17:46 UTC, gregmccoy commented on project/components/resource_request/schemas.py
> +    message: str = None
I had to use ugly Unions as this project is on 3.9

2022-10-28 17:46 UTC, gregmccoy commented on project/components/resource_request/schemas.py
>      completed_at: datetime = None
Done

2022-10-28 17:46 UTC, gregmccoy commented on project/components/resource_request/schemas.py
> +    vm_connections: dict = None
Done

2022-10-28 17:47 UTC, gregmccoy commented on tests/components/resource_request/test_views.py
> +        }
They've been added to the generator

2022-10-28 17:50 UTC, gregmccoy commented on tests/components/resource_request/test_views.py
> +    async def test_create_resource_request_connections_200(
I repurposed these tests to test the case where vm_connections and message are None. I've adjusted the name slightly: 
`test_create_resource_request_without_message_200`
I hope that's an ok compromise, I personally like the super long test names and I prefer adding the status  code as we do that most other places in our code.

2022-11-01 15:04 UTC, vmoshynskyi requested changes
Thank you for your code edits. Please check my last comments.

2022-11-01 15:40 UTC, merged